import { execSync } from 'child_process';

export async function createSecurityPR({
  octokit, REPO_OWNER, REPO_NAME, BASE_BRANCH,
  allFixes, issues_found, manual_actions_required, summary
}) {
  const timestamp = new Date().toISOString().slice(0, 19).replace(/:/g, '-');
  const newBranch = `claude-security-fix-${timestamp}`;

  execSync('git config user.name "Claude Security Bot"');
  execSync('git config user.email "claude-security@bot.noreply"');

  execSync(`git checkout -b ${newBranch}`);

  for (const fix of allFixes) {
    execSync(`git add "${fix.file}"`);
  }

  const issueCount = issues_found?.length || 0;
  execSync(`git commit -m "fix: Claude security auto-fix (${issueCount} issues)"`);

  execSync(`git push origin ${newBranch}`);
  console.log(`Pushed branch: ${newBranch}`);

  const severityEmoji = { critical: '🔴', high: '🟠', medium: '🟡', low: '🟢' };

  const issuesList = (issues_found || [])
    .map(i => `- ${severityEmoji[i.severity] || '⚪'} **[${i.severity.toUpperCase()}]** \`${i.file}\` — ${i.description}`)
    .join('\n');

  const fixesList = allFixes
    .map(f => `- \`${f.file}\`${f.reason ? ` — ${f.reason}` : ''}`)
    .join('\n');

  const manualList = (manual_actions_required || [])
    .map(a => `-  **[${a.severity.toUpperCase()}]** ${a.action}`)
    .join('\n');

  const prBody = `## Claude Security Auto-Fix

${summary}

---

### Issues Found (${issueCount})
${issuesList || '_No issues found_'}

---

### Files Modified
${fixesList || '_No files modified_'}

${manualList ? `---\n\n### Manual Actions Required\n${manualList}\n` : ''}
---

> This PR was automatically generated by Claude Security Bot.
> Review the changes before merging.`;

  const pr = await octokit.pulls.create({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    title: ` Security Fix: ${issueCount} issue${issueCount !== 1 ? 's' : ''} found and fixed`,
    body: prBody,
    head: newBranch,
    base: BASE_BRANCH,
  });

  console.log(`\n PR created: ${pr.data.html_url}`);
}
