// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

async function logAuthEvent(event: string, userId: string | null, details: Record<string, any>) {
  console.log(`[AUTH] ${event} - User: ${userId ?? 'unknown'}:`, JSON.stringify(details));
  // In production, write to a dedicated audit_logs table
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      await logAuthEvent('auth_failed', null, { reason: 'no_headers' });
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      await logAuthEvent('auth_failed', null, { reason: 'no_auth_header' });
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      await logAuthEvent('auth_failed', null, { reason: 'invalid_auth_type' });
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      await logAuthEvent('auth_failed', null, { reason: 'empty_token' });
      throw new Error('Unauthorized: No token provided');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      await logAuthEvent('auth_failed', null, { reason: 'invalid_token', error: error?.message });
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      await logAuthEvent('auth_failed', null, { reason: 'no_user_id' });
      throw new Error('Unauthorized: No user ID found in token');
    }

    await logAuthEvent('auth_success', data.claims.sub, { 
      email: data.claims.email,
      timestamp: new Date().toISOString(),
    });

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
